lib/rbnacl/simple_box.rb

Should make http://www.rubydoc.info/github/cryptosphere/rbnacl/master/RbNaCl/SimpleBox less confusing.

Use the correct class name in RDoc for SimpleBox

---

.travis.yml
Gemfile

Presently pinned to 1.0.0 and 1.0.3 respectively
@namelessjon I think this is what you were after...

Test both minimum supported and latest released libsodium

---

lib/rbnacl/hash.rb
lib/rbnacl/hash/blake2b.rb
lib/rbnacl/test_vectors.rb
lib/rbnacl/util.rb
spec/rbnacl/hash/blake2b_spec.rb

They are exposed as options on the hash constructor.  Strings are
zero-padded out to 16 bytes.  If they are not provided then a blank
string is passed into the hash.
Need to add some tests, but I've checked against the sodium vectors at least.

Add salt/personalisation strings for Blake2b

---

CHANGES.md
README.md
lib/rbnacl.rb
lib/rbnacl/version.rb

Thread.exclusive is deprecated in Ruby 2.3
We can hopefully rely on require to only run in a single thread at a time

Remove use of Thread.exclusive when initializing library

---

.rubocop.yml
README.md
lib/rbnacl/auth.rb
lib/rbnacl/boxes/curve25519xsalsa20poly1305.rb
lib/rbnacl/boxes/curve25519xsalsa20poly1305/private_key.rb
lib/rbnacl/hash.rb
lib/rbnacl/hash/blake2b.rb
lib/rbnacl/key_comparator.rb
lib/rbnacl/password_hash/scrypt.rb
lib/rbnacl/secret_boxes/xsalsa20poly1305.rb
lib/rbnacl/self_test.rb
lib/rbnacl/signatures/ed25519/signing_key.rb
lib/rbnacl/signatures/ed25519/verify_key.rb
lib/rbnacl/simple_box.rb
lib/rbnacl/sodium/version.rb
lib/rbnacl/test_vectors.rb
lib/rbnacl/util.rb
lib/rbnacl/version.rb

- Add `.rubocop_todo.yml` file and reference it on settings file
- Apply recent rubocop autocorrections to code base

Improve rubocop settings

---

lib/rbnacl/signatures/ed25519/signing_key.rb
spec/rbnacl/signatures/ed25519/signing_key_spec.rb

As per our Twitter DM discussion today. Let me know if you want me to modify anything.  Thanks.

Expose the internal @signing_key value in RbNaCl::Signatures::Ed25519 as #keypair

---

.rubocop.yml
.travis.yml
README.md
rbnacl.gemspec

- Prior major Ruby versions are EOL or soon-to-be EOL
- 2.2.6 is the latest release of the 2.2 series

Require Ruby 2.2.6+

---

.travis.yml

This slightly decreases overall build time by letting the other builds run in
parallel with the (longer) JRuby build

Run JRuby first in CI

---

lib/rbnacl/password_hash.rb
lib/rbnacl/password_hash/argon2.rb

this prevents an unpleasant ruby segfault if you happen to pass nil as the digest to `PasswordHash.argon2_valid?(password, digest)`

bugfix: prevent segfault if pwhash_str_verify is passed nil

---

lib/rbnacl/group_elements/curve25519.rb
spec/rbnacl/group_element_spec.rb

(Picking up on @paragonie-scott's work from #153)
This fixes the RuboCop errors from @paragonie-scott's #153 PR, adds a test, and adopts a belt-and-suspenders approach by trying to detect degenerate keys eagerly (still also handling errors surfaced from libsodium itself)

Raise error on degenerate keys (fixes #152)

---

README.md

Since ruby 2.4.2 is run on travis, it should be safe to assume it's supported. So let's add it to the readme.

Add ruby 2.4.2 to the supported versions

---

.rubocop.yml
lib/rbnacl/hmac/sha256.rb
lib/rbnacl/hmac/sha512.rb
lib/rbnacl/hmac/sha512256.rb
lib/rbnacl/test_vectors.rb
lib/rbnacl/util.rb
spec/rbnacl/authenticators/poly1305_spec.rb
spec/rbnacl/hmac/sha256_spec.rb
spec/rbnacl/hmac/sha512256_spec.rb
spec/rbnacl/hmac/sha512_spec.rb
spec/rbnacl/util_spec.rb
spec/shared/authenticator.rb
spec/shared/hmac.rb
spec/spec_helper.rb

Hi,
Here is my PR with non 32 keys supporting.
HMAC RFC 2104: https://tools.ietf.org/html/rfc2104#section-3
Thanks!

HMAC-SHA256/512 non 32 byte keys supporting

---

lib/rbnacl/random.rb

https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/randombytes.h#L35
defines `randombytes_buf` buffer size as `size_t`:
```c
void randombytes_buf(void * const buf, const size_t size);
```
but rbnacl defines it as `unsigned long long`:
```ruby
sodium_function :c_random_bytes,
:randombytes_buf,
%i[pointer ulong_long]
```
This manifests as an error on 32-bit big-endian platforms because `size_t`
is 32-bit there and `unsigned long long` is 64-bit.
I've found it as a testsuite crash on powerpc32:
```
#1  0x0fb93580 in abort () from /lib/libc.so.6
#2  0x0f622da8 in sodium_misuse () at /dev/shm/portage/dev-libs/libsodium-1.0.16-r1/work/libsodium-1.0.16/src/libsodium/sodium/core.c:216
#3  0x0f629d8c in randombytes_sysrandom_buf (buf=0x110a68f0, size=258618072)
at …
```

rbnacl: fix byffer size type in randombytes_buf binding

---

lib/rbnacl.rb
lib/rbnacl/aead/xchacha20poly1305_ietf.rb
lib/rbnacl/test_vectors.rb
spec/rbnacl/aead/xchacha20poly1305_ietf_spec.rb

Pretty self explanatory. This cipher is explicitly required by some things (i.e. [paseto]( https://github.com/paragonie/paseto/blob/master/docs/01-Protocol-Versions/Version2.md#encrypt)), so it'd be nice if we could use it directly.
See mguymon/paseto.rb#1 for a working example.

Add support for XChaCha20-Poly1305

---

lib/rbnacl/init.rb
lib/rbnacl/sodium.rb

Hi, this PR allows rbnacl to work with Heroku out-of-the-box (since Heroku is a pretty popular platform for Ruby developers). FFI allows you to specify [alternate file names](https://github.com/ffi/ffi/wiki/Loading-Libraries), so it shouldn't cause any issues for other platforms.
Tested on Mac, the heroku-16 stack, and the heroku-18 stack.

Support for Heroku

---

lib/rbnacl/hash/blake2b.rb

Do not assume anything about its internal structure. This is now an opaque array.

Fix the generichash state definition

---

lib/rbnacl/signatures/ed25519/signing_key.rb
lib/rbnacl/signatures/ed25519/verify_key.rb
spec/rbnacl/signatures/ed25519/signing_key_spec.rb
spec/rbnacl/signatures/ed25519/verify_key_spec.rb

- Renames methods to `sign_attached` and `verify_attached`
- Implements the detached API in terms of the attached API

signatures: Cleanups for attached signature API

---

lib/rbnacl/hmac/sha256.rb
lib/rbnacl/hmac/sha512.rb
lib/rbnacl/hmac/sha512256.rb

When running with ffi-1.2 the following warning is produced.
[DEPRECATION] Struct layout is already defined for class RbNaCl::HMAC::State. Redefinition as in /bundle/ruby/2.5.0/gems/rbnacl-7.1.0/lib/rbnacl/hmac/sha512256.rb:103:in `<class:State>' will be disallowed in ffi-2.0.
It seems these three files each define a `RbNaCl::HMAC::State` class.
The proposal presented here, nests the classes inside the main class of the file. Hence, three separate classes `RbNaCl::HMAC::SHA256::State`, `RbNaCl::HMAC::SHA512::State`, and `RbNaCl::HMAC::SHA512256::State` are defined instead.
Fixes #205

Resolve FFI deprecation warning

---

rbnacl.gemspec

Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `source_code_uri`, and `wiki_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/rbnacl), via the rubygems API, and the `gem` and `bundle` command-line tools with the next release.

Add project metadata to the gemspec

---

lib/rbnacl/signatures/ed25519/signing_key.rb
lib/rbnacl/signatures/ed25519/verify_key.rb
lib/rbnacl/test_vectors.rb
spec/rbnacl/signatures/ed25519/signing_key_spec.rb
spec/rbnacl/signatures/ed25519/verify_key_spec.rb

Don't know if it's the right place to add these helpers or If I did any unintended mistakes or more tests need to be added!
If this need to be moved to `Util` module or somewhere else, just let me know.
https://libsodium.gitbook.io/doc/advanced/ed25519-curve25519 should be read for anyone who uses this (we already used this in one of our projects).
Resolves #204.

add ed25519 to curve25519 conversion helpers

---

lib/rbnacl/util.rb
spec/shared/hmac.rb

Noticed this little issue when empty keys are passed to the hmac algorithms.

Fix error message generation when empty hmac key is given

---

lib/rbnacl/password_hash.rb
lib/rbnacl/password_hash/scrypt.rb
lib/rbnacl/test_vectors.rb
spec/rbnacl/password_hash/scrypt_spec.rb

This pull request adds two libsodium constants `OPSLIMIT_SENSITIVE` and `MEMLIMIT_SENSITIVE` as default values for the `opslimit` and `memlimit` parameters to `RbNaCl::PasswordHash.scrypt`.
Here is an example of these values being used in the wild: https://github.com/jedisct1/minisign/blob/573988d2355172b6e050fa3fdc974abd3e476988/src/minisign.c#L357-L358 
Also for the test case, I updated the expected digest so that there wouldn't be two `scrypt_digest`s.

Use libsodium constants for scrypt params

---

lib/rbnacl/init.rb
lib/rbnacl/sodium.rb

We use RbNaCl with Alpine 3.19 and we see the below errors
```
#40 7.090 Could not open library 'libsodium.so': Error loading shared library libsodium.so: No such file or directory.
#40 7.090 Could not open library 'libsodium.so.18': Error loading shared library libsodium.so.18: No such file or directory.
#40 7.090 Could not open library 'libsodium.so.23': Error loading shared library libsodium.so.23: No such file or directory.
```
After looking into [the content of Alpine](https://pkgs.alpinelinux.org/contents?file=&path=&name=libsodium&branch=edge&repo=main&arch=aarch64), it looks like the file is now `libsodium.so.26`.

Support alpine 3.19 and up

---

.github/workflows/ci.yml
README.md

Add Ruby 3.3 to the CI Ruby version matrix to test against the current stable release of Ruby. Also update the `actions/checkout` GitHub Action to the current latest version.

Add Ruby 3.3 to the test matrix and update the checkout Github Action to the latest version
